[package]
name = "luno"
version = "0.1.0"
authors = ["Duncan Dean <duncangleeddean@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.11.25"
hyper-tls = "0.1.4"
url = "1.7.2"
futures = "0.1.0"
tokio-core = "0.1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"

