[package]
name = "luno"
version = "0.1.0"
authors = ["Duncan Dean <duncangleeddean@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
strum = "0.15.0"
strum_macros = "0.15.0"
